job('First-Maven-Project-Via-DSLjob') {
    logRotator(-1, 1)
    description("First Maven job generated by the DSL on ${new Date()}. The project is a Maven project hosted on GitHub.")

    jdk('OpenJDK-11') // Using JDK 11, make sure 'OpenJDK-11' is the correct JDK installation name

    scm {
        git("https://github.com/lavkumar809/myrepo1.git", "master")
    }
    
    triggers {
        scm('* * * * *')
    }
    
    steps {
        maven {
            mavenName('Maven-3.9.2')
            goals('clean package')
            pom('pom.xml')
        }
    }

    publishers {
        archiveArtifacts '**/*.jar'
    }
}
