job('Generated-Maven-Project') {
    description("First maven job generated by the DSL on ${new Date()}, the project is a maven project hosted on github")

    jdk('OpenJDK-11')

    scm {
        git {
            remote {
                url('https://github.com/lavkumar809/myrepo1.git')
            }
            branches('master')
        }
    }

    triggers {
        scm('* * * * *')
    }

    steps {
        maven('clean package', 'pom.xml')
    }

    publishers {
        archiveArtifacts '**/*.jar'
    }

    wrappers {
        timestamps()
    }
}
